# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kissmig_c <- function(d, s, dim, it, pe, pc, ty, si, nThreads, randRingSize) {
    .Call(`_kissmig_kissmig_c`, d, s, dim, it, pe, pc, ty, si, nThreads, randRingSize)
}

